// Derived from COACTVW.bms fields: ACCTSID, ACSTTUS, ADTOPEN, ACRDLIM, AEXPDT,
// ACSHLIM, AREISDT, ACURBAL, ACRCYCR, AADDGRP, ACRCYDB, ACSTNUM, ACSTSSN,
// ACSTDOB, ACSTFCO, ACSFNAM, ACSMNAM, ACSLNAM, ACSADL1, ACSADL2, ACSSTTE,
// ACSZIPC, ACSCITY, ACSCTRY, ACSPHN1, ACSPHN2, ACSGOVT, ACSEFTC, ACSPFLG
export const AccountViewLocators = {
  screenTitle: 'text=View Account',
  accountNumber: '[data-testid="acctsid"], #acctsid, input[name="accountNumber"]',
  activeStatus: '[data-testid="acsttus"], #acsttus',
  dateOpened: '[data-testid="adtopen"], #adtopen',
  creditLimit: '[data-testid="acrdlim"], #acrdlim',
  expiryDate: '[data-testid="aexpdt"], #aexpdt',
  cashCreditLimit: '[data-testid="acshlim"], #acshlim',
  reissueDate: '[data-testid="areisdt"], #areisdt',
  currentBalance: '[data-testid="acurbal"], #acurbal',
  currentCycleCredit: '[data-testid="acrcycr"], #acrcycr',
  accountGroup: '[data-testid="aaddgrp"], #aaddgrp',
  currentCycleDebit: '[data-testid="acrcydb"], #acrcydb',
  customerId: '[data-testid="acstnum"], #acstnum',
  ssn: '[data-testid="acstssn"], #acstssn',
  dateOfBirth: '[data-testid="acstdob"], #acstdob',
  ficoScore: '[data-testid="acstfco"], #acstfco',
  firstName: '[data-testid="acsfnam"], #acsfnam',
  middleName: '[data-testid="acsmnam"], #acsmnam',
  lastName: '[data-testid="acslnam"], #acslnam',
  addressLine1: '[data-testid="acsadl1"], #acsadl1',
  addressLine2: '[data-testid="acsadl2"], #acsadl2',
  state: '[data-testid="acsstte"], #acsstte',
  zipCode: '[data-testid="acszipc"], #acszipc',
  city: '[data-testid="acscity"], #acscity',
  country: '[data-testid="acsctry"], #acsctry',
  phone1: '[data-testid="acsphn1"], #acsphn1',
  phone2: '[data-testid="acsphn2"], #acsphn2',
  govtId: '[data-testid="acsgovt"], #acsgovt',
  eftAccountId: '[data-testid="acseftc"], #acseftc',
  primaryCardHolder: '[data-testid="acspflg"], #acspflg',
  errorMessage: '[data-testid="errmsg"], #errmsg',
  infoMessage: '[data-testid="infomsg"], #infomsg',
};
