// Derived from COACTUP.bms - same fields as accountView but editable (UNPROT),
// plus date fields split into year/month/day (OPNYEAR, OPNMON, OPNDAY, EXPYEAR,
// EXPMON, EXPDAY, RISYEAR, RISMON, RISDAY, DOBYEAR, DOBMON, DOBDAY),
// SSN split (ACTSSN1, ACTSSN2, ACTSSN3), phone split (ACSPH1A/B/C, ACSPH2A/B/C)
export const AccountUpdateLocators = {
  screenTitle: 'text=Update Account',
  accountNumber: '[data-testid="acctsid"], #acctsid',
  activeStatus: '[data-testid="acsttus"], #acsttus, input[name="activeStatus"]',
  openedYear: '[data-testid="opnyear"], #opnyear',
  openedMonth: '[data-testid="opnmon"], #opnmon',
  openedDay: '[data-testid="opnday"], #opnday',
  creditLimit: '[data-testid="acrdlim"], #acrdlim, input[name="creditLimit"]',
  expiryYear: '[data-testid="expyear"], #expyear',
  expiryMonth: '[data-testid="expmon"], #expmon',
  expiryDay: '[data-testid="expday"], #expday',
  cashCreditLimit: '[data-testid="acshlim"], #acshlim',
  reissueYear: '[data-testid="risyear"], #risyear',
  reissueMonth: '[data-testid="rismon"], #rismon',
  reissueDay: '[data-testid="risday"], #risday',
  currentBalance: '[data-testid="acurbal"], #acurbal',
  currentCycleCredit: '[data-testid="acrcycr"], #acrcycr',
  accountGroup: '[data-testid="aaddgrp"], #aaddgrp',
  currentCycleDebit: '[data-testid="acrcydb"], #acrcydb',
  customerId: '[data-testid="acstnum"], #acstnum',
  ssn1: '[data-testid="actssn1"], #actssn1',
  ssn2: '[data-testid="actssn2"], #actssn2',
  ssn3: '[data-testid="actssn3"], #actssn3',
  dobYear: '[data-testid="dobyear"], #dobyear',
  dobMonth: '[data-testid="dobmon"], #dobmon',
  dobDay: '[data-testid="dobday"], #dobday',
  ficoScore: '[data-testid="acstfco"], #acstfco',
  firstName: '[data-testid="acsfnam"], #acsfnam',
  middleName: '[data-testid="acsmnam"], #acsmnam',
  lastName: '[data-testid="acslnam"], #acslnam',
  addressLine1: '[data-testid="acsadl1"], #acsadl1',
  addressLine2: '[data-testid="acsadl2"], #acsadl2',
  state: '[data-testid="acsstte"], #acsstte',
  zipCode: '[data-testid="acszipc"], #acszipc',
  city: '[data-testid="acscity"], #acscity',
  country: '[data-testid="acsctry"], #acsctry',
  phone1Area: '[data-testid="acsph1a"], #acsph1a',
  phone1Prefix: '[data-testid="acsph1b"], #acsph1b',
  phone1Line: '[data-testid="acsph1c"], #acsph1c',
  phone2Area: '[data-testid="acsph2a"], #acsph2a',
  phone2Prefix: '[data-testid="acsph2b"], #acsph2b',
  phone2Line: '[data-testid="acsph2c"], #acsph2c',
  govtId: '[data-testid="acsgovt"], #acsgovt',
  eftAccountId: '[data-testid="acseftc"], #acseftc',
  primaryCardHolder: '[data-testid="acspflg"], #acspflg',
  errorMessage: '[data-testid="errmsg"], #errmsg',
  infoMessage: '[data-testid="infomsg"], #infomsg',
};
