// Derived from COTRN01.bms: TRNIDIN (search input), TRNID, CARDNUM, TTYPCD, TCATCD,
// TRNSRC, TDESC, TRNAMT, TORIGDT, TPROCDT, MID, MNAME, MCITY, MZIP
export const TransactionViewLocators = {
  screenTitle: 'text=View Transaction',
  searchInput: '[data-testid="trnidin"], #trnidin, input[name="transactionId"]',
  transactionId: '[data-testid="trnid"], #trnid',
  cardNumber: '[data-testid="cardnum"], #cardnum',
  typeCode: '[data-testid="ttypcd"], #ttypcd',
  categoryCode: '[data-testid="tcatcd"], #tcatcd',
  source: '[data-testid="trnsrc"], #trnsrc',
  description: '[data-testid="tdesc"], #tdesc',
  amount: '[data-testid="trnamt"], #trnamt',
  originDate: '[data-testid="torigdt"], #torigdt',
  processDate: '[data-testid="tprocdt"], #tprocdt',
  merchantId: '[data-testid="mid"], #mid',
  merchantName: '[data-testid="mname"], #mname',
  merchantCity: '[data-testid="mcity"], #mcity',
  merchantZip: '[data-testid="mzip"], #mzip',
  errorMessage: '[data-testid="errmsg"], #errmsg',
  fetchHint: 'text=ENTER=Fetch',
  backHint: 'text=F3=Back',
  clearHint: 'text=F4=Clear',
  browseHint: 'text=F5=Browse Tran',
};
