// Derived from COTRN02.bms: ACTIDIN (account input), CARDNIN (card input),
// TTYPCD, TCATCD, TRNSRC, TDESC, TRNAMT, TORIGDT, TPROCDT, MID, MNAME,
// MCITY, MZIP, CONFIRM (Y/N)
export const TransactionAddLocators = {
  screenTitle: 'text=Add Transaction',
  accountInput: '[data-testid="actidin"], #actidin, input[name="accountId"]',
  cardInput: '[data-testid="cardnin"], #cardnin, input[name="cardNumber"]',
  typeCode: '[data-testid="ttypcd"], #ttypcd, input[name="typeCode"]',
  categoryCode: '[data-testid="tcatcd"], #tcatcd, input[name="categoryCode"]',
  source: '[data-testid="trnsrc"], #trnsrc, input[name="source"]',
  description: '[data-testid="tdesc"], #tdesc, input[name="description"]',
  amount: '[data-testid="trnamt"], #trnamt, input[name="amount"]',
  originDate: '[data-testid="torigdt"], #torigdt, input[name="originDate"]',
  processDate: '[data-testid="tprocdt"], #tprocdt, input[name="processDate"]',
  merchantId: '[data-testid="mid"], #mid, input[name="merchantId"]',
  merchantName: '[data-testid="mname"], #mname, input[name="merchantName"]',
  merchantCity: '[data-testid="mcity"], #mcity, input[name="merchantCity"]',
  merchantZip: '[data-testid="mzip"], #mzip, input[name="merchantZip"]',
  confirm: '[data-testid="confirm"], #confirm, input[name="confirm"]',
  errorMessage: '[data-testid="errmsg"], #errmsg',
  continueHint: 'text=ENTER=Continue',
  backHint: 'text=F3=Back',
  clearHint: 'text=F4=Clear',
  copyLastHint: 'text=F5=Copy Last Tran',
};
