export type FieldSpec = {
  name: string;
  label: string;
  length: number;
  row: number;
  col: number;
  protected?: boolean;
  password?: boolean;
};

export type MapSpec = {
  code: string;
  title: string;
  route: string;
  admin?: boolean;
  fields: FieldSpec[];
};

const common = [
  { name: "trnname", label: "Transaction", length: 4, row: 1, col: 7, protected: true },
  { name: "title01", label: "CARDDEMO", length: 40, row: 1, col: 21, protected: true },
  { name: "curdate", label: "Date", length: 8, row: 1, col: 71, protected: true },
  { name: "pgmname", label: "Program", length: 8, row: 2, col: 7, protected: true },
  { name: "title02", label: "CARD DEMONSTRATION APPLICATION", length: 40, row: 2, col: 21, protected: true },
  { name: "curtime", label: "Time", length: 8, row: 2, col: 71, protected: true },
] satisfies FieldSpec[];

const fields = (...items: FieldSpec[]) => [...common, ...items];
const input = (name: string, label: string, length: number, row: number, col: number, options: Partial<FieldSpec> = {}): FieldSpec =>
  ({ name, label, length, row, col, ...options });

export const MAPS: Record<string, MapSpec> = {
  COSGN00: { code: "COSGN00", title: "CARDDEMO SIGNON", route: "/signon", fields: fields(input("userId", "User ID", 8, 19, 43), input("password", "Password", 8, 20, 43, { password: true }), input("message", "Message", 78, 23, 1, { protected: true })) },
  COMEN01: { code: "COMEN01", title: "CARDDEMO MAIN MENU", route: "/menu", fields: fields(...Array.from({ length: 12 }, (_, i) => input(`option${i + 1}`, `${i + 1}`, 40, 6 + i, 20, { protected: true })), input("option", "Option", 2, 20, 41), input("message", "Message", 78, 23, 1, { protected: true })) },
  COADM01: { code: "COADM01", title: "CARDDEMO ADMIN MENU", route: "/admin/menu", admin: true, fields: fields(...Array.from({ length: 12 }, (_, i) => input(`option${i + 1}`, `${i + 1}`, 40, 6 + i, 20, { protected: true })), input("option", "Option", 2, 20, 41), input("message", "Message", 78, 23, 1, { protected: true })) },
  COACTVW: { code: "COACTVW", title: "ACCOUNT VIEW", route: "/accounts/view", fields: fields(input("accountId", "Account ID", 11, 5, 38), input("status", "Status", 1, 5, 70, { protected: true }), input("openDate", "Date Opened", 10, 6, 17, { protected: true }), input("creditLimit", "Credit Limit", 15, 6, 61, { protected: true }), input("expirationDate", "Expiration Date", 10, 7, 17, { protected: true }), input("cashLimit", "Cash Limit", 15, 7, 61, { protected: true }), input("reissueDate", "Reissue Date", 10, 8, 17, { protected: true }), input("currentBalance", "Current Balance", 15, 8, 61, { protected: true }), input("cycleCredit", "Cycle Credit", 15, 9, 61, { protected: true }), input("groupId", "Address Group", 10, 10, 23, { protected: true }), input("cycleDebit", "Cycle Debit", 15, 10, 61, { protected: true }), input("customerNumber", "Customer Number", 9, 12, 23, { protected: true }), input("ssn", "SSN", 12, 12, 54, { protected: true }), input("dateOfBirth", "Date of Birth", 10, 13, 23, { protected: true }), input("ficoScore", "FICO Score", 3, 13, 61, { protected: true }), input("firstName", "First Name", 25, 15, 1, { protected: true }), input("middleName", "Middle Name", 25, 15, 28, { protected: true }), input("lastName", "Last Name", 25, 15, 55, { protected: true }), input("addressLine1", "Address Line 1", 50, 16, 10, { protected: true }), input("state", "State", 2, 16, 73, { protected: true }), input("addressLine2", "Address Line 2", 50, 17, 10, { protected: true }), input("zip", "ZIP", 5, 17, 73, { protected: true }), input("city", "City", 50, 18, 10, { protected: true }), input("country", "Country", 3, 18, 73, { protected: true }), input("phone1", "Phone 1", 13, 19, 10, { protected: true }), input("governmentId", "Government ID", 20, 19, 58, { protected: true }), input("phone2", "Phone 2", 13, 20, 10, { protected: true }), input("eftAccountId", "EFT Account", 10, 20, 41, { protected: true }), input("message", "Message", 78, 23, 1, { protected: true })) },
  COACTUP: { code: "COACTUP", title: "ACCOUNT UPDATE", route: "/accounts/update", fields: fields(input("accountId", "Account ID", 11, 5, 38), input("activeStatus", "Active Status", 1, 5, 70), input("openYear", "Open Year", 4, 6, 17), input("openMonth", "Open Month", 2, 6, 24), input("openDay", "Open Day", 2, 6, 29), input("creditLimit", "Credit Limit", 15, 6, 61), input("expirationYear", "Expiration Year", 4, 7, 17), input("expirationMonth", "Expiration Month", 2, 7, 24), input("expirationDay", "Expiration Day", 2, 7, 29), input("cashLimit", "Cash Limit", 15, 7, 61), input("reissueYear", "Reissue Year", 4, 8, 17), input("reissueMonth", "Reissue Month", 2, 8, 24), input("reissueDay", "Reissue Day", 2, 8, 29), input("currentBalance", "Current Balance", 15, 8, 61), input("cycleCredit", "Cycle Credit", 15, 9, 61), input("groupId", "Address Group", 10, 10, 23), input("cycleDebit", "Cycle Debit", 15, 10, 61), input("firstName", "First Name", 25, 15, 1), input("middleName", "Middle Name", 25, 15, 28), input("lastName", "Last Name", 25, 15, 55), input("addressLine1", "Address Line 1", 50, 16, 10), input("state", "State", 2, 16, 73), input("addressLine2", "Address Line 2", 50, 17, 10), input("zip", "ZIP", 5, 17, 73), input("city", "City", 50, 18, 10), input("country", "Country", 3, 18, 73), input("phone1", "Phone 1", 13, 19, 10), input("phone2", "Phone 2", 13, 20, 10), input("eftAccountId", "EFT Account", 10, 20, 41), input("confirm", "Confirm", 1, 20, 78), input("message", "Message", 78, 23, 1, { protected: true })) },
  COCRDLI: { code: "COCRDLI", title: "CREDIT CARD LIST", route: "/cards", fields: fields(input("accountId", "Account ID Filter", 11, 6, 44), input("cardNumber", "Card Number Filter", 16, 7, 44), ...Array.from({ length: 7 }, (_, i) => input(`select${i + 1}`, "Select", 1, 11 + i, 12, { protected: true })), input("message", "Message", 78, 23, 1, { protected: true })) },
  COCRDSL: { code: "COCRDSL", title: "CREDIT CARD DETAIL", route: "/cards/detail", fields: fields(input("accountId", "Account ID", 11, 7, 45), input("cardNumber", "Card Number", 16, 8, 45), input("cardName", "Name on Card", 50, 11, 25, { protected: true }), input("status", "Card Active Y/N", 1, 13, 25, { protected: true }), input("expirationMonth", "Expiry Month", 2, 15, 25, { protected: true }), input("expirationYear", "Expiry Year", 4, 15, 30, { protected: true }), input("expirationDay", "Expiry Day", 2, 15, 36, { protected: true }), input("message", "Message", 80, 23, 1, { protected: true })) },
  COCRDUP: { code: "COCRDUP", title: "CREDIT CARD UPDATE", route: "/cards/update", fields: fields(input("accountId", "Account ID", 11, 7, 45, { protected: true }), input("cardNumber", "Card Number", 16, 8, 45), input("cardName", "Name on Card", 50, 11, 25), input("status", "Card Active Y/N", 1, 13, 25), input("expirationMonth", "Expiry Month", 2, 15, 25), input("expirationYear", "Expiry Year", 4, 15, 30), input("expirationDay", "Expiry Day", 2, 15, 36, { protected: true }), input("confirm", "Confirm", 1, 17, 25), input("message", "Message", 80, 23, 1, { protected: true })) },
  COTRN00: { code: "COTRN00", title: "TRANSACTION LIST", route: "/transactions", fields: fields(input("transactionId", "Transaction ID Filter", 16, 6, 21), ...Array.from({ length: 10 }, (_, i) => input(`select${i + 1}`, "Select", 1, 10 + i, 3)), input("message", "Message", 78, 23, 1, { protected: true })) },
  COTRN01: { code: "COTRN01", title: "TRANSACTION VIEW", route: "/transactions/view", fields: fields(input("transactionId", "Transaction ID", 16, 6, 21), input("cardNumber", "Card Number", 16, 10, 58, { protected: true }), input("typeCode", "Type Code", 2, 12, 15, { protected: true }), input("categoryCode", "Category Code", 4, 12, 36, { protected: true }), input("source", "Source", 10, 12, 54, { protected: true }), input("description", "Description", 60, 14, 19, { protected: true }), input("amount", "Amount", 12, 16, 14, { protected: true }), input("origDate", "Original Date", 10, 16, 42, { protected: true }), input("procDate", "Processed Date", 10, 16, 68, { protected: true }), input("merchantId", "Merchant ID", 9, 18, 19, { protected: true }), input("merchantName", "Merchant Name", 30, 18, 48, { protected: true }), input("merchantCity", "Merchant City", 25, 20, 21, { protected: true }), input("merchantZip", "Merchant ZIP", 10, 20, 67, { protected: true }), input("message", "Message", 78, 23, 1, { protected: true })) },
  COTRN02: { code: "COTRN02", title: "TRANSACTION ADD", route: "/transactions/add", fields: fields(input("accountId", "Account ID", 11, 6, 21), input("cardNumber", "Card Number", 16, 6, 55), input("typeCode", "Type Code", 2, 10, 15), input("categoryCode", "Category Code", 4, 10, 36), input("source", "Source", 10, 10, 54), input("description", "Description", 60, 12, 19), input("amount", "Amount", 12, 14, 14), input("origDate", "Original Date", 10, 14, 42), input("procDate", "Processed Date", 10, 14, 68), input("merchantId", "Merchant ID", 9, 16, 19), input("merchantName", "Merchant Name", 30, 16, 48), input("merchantCity", "Merchant City", 25, 18, 21), input("merchantZip", "Merchant ZIP", 10, 18, 67), input("confirm", "Confirm", 1, 21, 63), input("message", "Message", 78, 23, 1, { protected: true })) },
  COBIL00: { code: "COBIL00", title: "BILL PAYMENT", route: "/bill-payment", fields: fields(input("accountId", "Account ID", 11, 6, 21), input("currentBalance", "Current Balance", 14, 11, 32, { protected: true }), input("confirm", "Confirm", 1, 15, 60), input("message", "Message", 78, 23, 1, { protected: true })) },
  CORPT00: { code: "CORPT00", title: "TRANSACTION REPORT", route: "/reports", fields: fields(input("monthly", "Monthly Report", 1, 7, 10), input("yearly", "Yearly Report", 1, 9, 10), input("custom", "Custom Report", 1, 11, 10), input("startMonth", "Start Month", 2, 13, 29), input("startDay", "Start Day", 2, 13, 34), input("startYear", "Start Year", 4, 13, 39), input("endMonth", "End Month", 2, 14, 29), input("endDay", "End Day", 2, 14, 34), input("endYear", "End Year", 4, 14, 39), input("confirm", "Confirm", 1, 19, 66), input("message", "Message", 78, 23, 1, { protected: true })) },
  COUSR00: { code: "COUSR00", title: "USER SECURITY LIST", route: "/admin/users", admin: true, fields: fields(input("userId", "User ID Filter", 8, 6, 21), ...Array.from({ length: 10 }, (_, i) => input(`select${i + 1}`, "Select", 1, 10 + i, 6, { protected: true })), input("message", "Message", 78, 23, 1, { protected: true })) },
  COUSR01: { code: "COUSR01", title: "ADD SECURITY USER", route: "/admin/users/add", admin: true, fields: fields(input("firstName", "First Name", 20, 8, 18), input("lastName", "Last Name", 20, 8, 56), input("userId", "User ID", 8, 11, 15), input("password", "Password", 8, 11, 55, { password: true }), input("userType", "User Type", 1, 14, 17), input("message", "Message", 78, 23, 1, { protected: true })) },
  COUSR02: { code: "COUSR02", title: "UPDATE SECURITY USER", route: "/admin/users/update", admin: true, fields: fields(input("userId", "User ID", 8, 6, 21), input("firstName", "First Name", 20, 11, 18), input("lastName", "Last Name", 20, 11, 56), input("password", "Password", 8, 13, 16, { password: true }), input("userType", "User Type", 1, 15, 17), input("message", "Message", 78, 23, 1, { protected: true })) },
  COUSR03: { code: "COUSR03", title: "DELETE SECURITY USER", route: "/admin/users/delete", admin: true, fields: fields(input("userId", "User ID", 8, 6, 21), input("firstName", "First Name", 20, 11, 18, { protected: true }), input("lastName", "Last Name", 20, 13, 18, { protected: true }), input("userType", "User Type", 1, 15, 17, { protected: true }), input("message", "Message", 78, 23, 1, { protected: true })) },
  COPAU00: { code: "COPAU00", title: "AUTHORIZATION SUMMARY", route: "/authorizations", fields: fields(input("accountId", "Account ID", 11, 6, 30), ...Array.from({ length: 5 }, (_, i) => input(`select${i + 1}`, "Select", 1, 10 + i, 3)), ...["transactionId", "authDate", "authTime", "authType", "approved", "status", "amount"].flatMap((name) => [1, 2, 3, 4, 5].map((row) => input(`${name}${row}`, name.replace(/([A-Z])/g, " $1"), name === "transactionId" ? 16 : name === "amount" ? 12 : name === "authType" ? 4 : 8, 9 + row, 8, { protected: true }))), input("message", "Message", 78, 23, 1, { protected: true })) },
  COPAU01: { code: "COPAU01", title: "AUTHORIZATION DETAIL", route: "/authorizations/detail", fields: fields(input("authorizationId", "Authorization ID", 8, 6, 25), input("accountId", "Account ID", 11, 6, 50, { protected: true }), input("cardNumber", "Card Number", 16, 8, 25, { protected: true }), input("transactionId", "Transaction ID", 15, 10, 25, { protected: true }), input("amount", "Amount", 14, 12, 25, { protected: true }), input("responseCode", "Response Code", 2, 14, 25, { protected: true }), input("matchStatus", "Match Status", 1, 16, 25, { protected: true }), input("fraud", "Fraud", 1, 18, 25), input("message", "Message", 78, 23, 1, { protected: true })) },
  COTRTLI: { code: "COTRTLI", title: "TRANSACTION TYPE LIST", route: "/admin/transaction-types", admin: true, fields: fields(...Array.from({ length: 8 }, (_, i) => input(`select${i + 1}`, "Select", 1, 8 + i, 3)), ...Array.from({ length: 8 }, (_, i) => input(`type${i + 1}`, "Type", 2, 8 + i, 17, { protected: true })), ...Array.from({ length: 8 }, (_, i) => input(`description${i + 1}`, "Description", 50, 8 + i, 25)), input("type", "Type", 2, 18, 15), input("description", "Description", 50, 18, 25), input("message", "Message", 78, 23, 1, { protected: true })) },
  COTRTUP: { code: "COTRTUP", title: "TRANSACTION TYPE UPDATE", route: "/admin/transaction-types/update", admin: true, fields: fields(input("type", "Type", 2, 8, 20), input("description", "Description", 50, 10, 20), input("confirm", "Confirm", 1, 14, 20), input("message", "Message", 78, 23, 1, { protected: true })) },
};

export const mapForPath = (path: string): MapSpec =>
  Object.values(MAPS).find((map) => map.route === path) ?? MAPS.COMEN01;
