{{- if and .Values.spring.datasource.username .Values.spring.datasource.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suitecrm-service.fullname" . }}-db
  labels:
    {{- include "suitecrm-service.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.spring.datasource.username | b64enc | quote }}
  password: {{ .Values.spring.datasource.password | b64enc | quote }}
{{- end }}
