server:
  port: 8080

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/carddemo
    username: carddemo
    password: carddemo
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: api-gateway
  flyway:
    schemas:
      - api-gateway
