-- V2: Expand leads with all AS-IS fields
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS email2 VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS email_opt_out BOOLEAN DEFAULT FALSE;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS invalid_email BOOLEAN DEFAULT FALSE;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS webtolead_email1 VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS webtolead_email2 VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS webtolead_email_opt_out VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS webtolead_invalid_email VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS alt_address_street VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS alt_address_city VARCHAR(100);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS alt_address_state VARCHAR(100);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS alt_address_postalcode VARCHAR(20);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS alt_address_country VARCHAR(100);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS status_description TEXT;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS lead_source_description TEXT;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS account_description TEXT;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS account_id UUID;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS contact_id UUID;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS opportunity_id UUID;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS opportunity_name VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS opportunity_amount VARCHAR(50);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS campaign_id UUID;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS campaign_name VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS referred_by VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS reports_to_id UUID;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS birthdate DATE;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS portal_name VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS portal_app VARCHAR(255);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS converted BOOLEAN DEFAULT FALSE;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS converted_date DATE;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS lawful_basis VARCHAR(100);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS date_reviewed DATE;
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS lawful_basis_source VARCHAR(100);
ALTER TABLE lead_schema.leads ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
