server:
  port: 8085

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/carddemo
    username: carddemo
    password: carddemo
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: transaction
  flyway:
    schemas:
      - transaction
